# Generated by Django 5.1.13 on 2026-04-13 00:26

import django.core.validators
import django.db.models.deletion
import the_keep.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('the_gatehouse', '0005_usernotification_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardboardTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('token', 'Token'), ('building', 'Building')], max_length=20)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DecreeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, null=True)),
                ('body', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(choices=[('single', 'Single'), ('decree', 'Decree')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FactionSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_text', models.TextField(blank=True, null=True)),
                ('action_image', models.ImageField(blank=True, null=True, upload_to='forge/action_icons/')),
                ('include_crafted_items', models.BooleanField(default=True)),
                ('layout_mode', models.CharField(choices=[('auto', 'Layout Auto'), ('horizontal', 'Layout Horizontal'), ('vertical', 'Layout Vertical')], default='auto', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CardboardSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='the_forge.cardboardtrack')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CardSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('decree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_slots', to='the_forge.decreesection')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='decreesection',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decrees', to='the_forge.factionsheet'),
        ),
        migrations.CreateModel(
            name='ContentBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('text', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField()),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_boxes', to='the_forge.factionsheet')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ForgedFaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction_name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, help_text='Enter a hex color code (e.g., #RRGGBB).', max_length=7, null=True, validators=[the_keep.utils.validate_hex_color])),
                ('background_preset', models.CharField(blank=True, choices=[('', '---'), ('cats', 'Marquise de Cat'), ('birds', 'Eyrie Dynasties'), ('wa', 'Woodland Alliance'), ('vb', 'Vagabond'), ('lizards', 'Lizard Cult'), ('otters', 'Riverfolk Company'), ('moles', 'Underground Duchy'), ('crows', 'Corvid Conspiracy'), ('rats', 'Lord of the Hundreds'), ('badgers', 'Keepers in Iron')], default='', help_text='Select a preset background, or upload your own below.', max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='forge/sheet_backgrounds/')),
                ('repeat_background_image', models.BooleanField(default=False)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_sheets', to='the_gatehouse.profile')),
            ],
        ),
        migrations.AddField(
            model_name='factionsheet',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_sheets', to='the_forge.forgedfaction'),
        ),
        migrations.CreateModel(
            name='FactionBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Moderate'), ('H', 'High')], default='N', max_length=1)),
                ('card_wealth', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Moderate'), ('H', 'High')], default='N', max_length=1)),
                ('aggression', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Moderate'), ('H', 'High')], default='N', max_length=1)),
                ('crafting_ability', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Moderate'), ('H', 'High')], default='N', max_length=1)),
                ('setup_order', models.CharField(default='X', max_length=1)),
                ('how_to_play_title', models.TextField(default='Playing the Faction')),
                ('how_to_play_text', models.TextField(blank=True, null=True)),
                ('faction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faction_backs', to='the_forge.forgedfaction')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('birdsong', 'Birdsong'), ('daylight', 'Daylight'), ('evening', 'Evening'), ('other', 'Other')], max_length=30)),
                ('number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('content_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='the_forge.contentbox')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_steps', to='the_forge.factionsheet')),
            ],
            options={
                'ordering': ['phase', 'number'],
            },
        ),
        migrations.AddField(
            model_name='cardboardtrack',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='the_forge.phasestep'),
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('type', models.CharField(choices=[('W', 'Warrior'), ('B', 'Building'), ('T', 'Token'), ('C', 'Card'), ('O', 'Other')], max_length=1)),
                ('small_icon', models.ImageField(blank=True, null=True, upload_to='forge/sheet_backgrounds/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='the_forge.factionback')),
            ],
        ),
        migrations.CreateModel(
            name='SetupCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('M', 'Militant'), ('I', 'Insurgent')], default='I', max_length=10)),
                ('reach', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_cards', to='the_forge.forgedfaction')),
            ],
        ),
        migrations.CreateModel(
            name='SetupStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_steps', to='the_forge.setupcard')),
                ('faction_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_steps', to='the_forge.factionback')),
            ],
        ),
        migrations.CreateModel(
            name='FactionAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='the_forge.factionsheet')),
            ],
        ),
        migrations.CreateModel(
            name='StepAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('cost', models.CharField(choices=[('action', 'Action'), ('item_sword', 'Sword'), ('item_hammer', 'Hammer'), ('item_crossbow', 'Crossbow'), ('item_coins', 'Coins'), ('item_boots', 'Boots'), ('item_tea', 'Tea'), ('item_bag', 'Bag'), ('item_torch', 'Torch'), ('item_any', 'Any Item'), ('card_fox', 'Fox'), ('card_mouse', 'Mouse'), ('card_rabbit', 'Rabbit'), ('card_bird', 'Bird'), ('card_nonbird', 'Non-Bird'), ('other', 'Other (Custom Image)')], default='action', max_length=20)),
                ('cost_image', models.ImageField(blank=True, null=True, upload_to='forge/cost_icons/')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='the_forge.phasestep')),
            ],
        ),
    ]
