# Generated by Django 5.1.13 on 2026-04-12 00:03

import django.db.models.deletion
import the_keep.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('the_gatehouse', '0005_usernotification_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardboardTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('token', 'Token'), ('building', 'Building')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DecreeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, null=True)),
                ('body', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(choices=[('single', 'Single'), ('decree', 'Decree')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CardboardSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='the_forge.cardboardtrack')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CardSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('decree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_slots', to='the_forge.decreesection')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='FactionSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction_name', models.CharField(max_length=100)),
                ('flavor_text', models.TextField(blank=True, null=True)),
                ('background_preset', models.CharField(blank=True, choices=[('', '---'), ('cats', 'Marquise de Cat'), ('birds', 'Eyrie Dynasties'), ('wa', 'Woodland Alliance'), ('vb', 'Vagabond'), ('lizards', 'Lizard Cult'), ('otters', 'Riverfolk Company'), ('moles', 'Underground Duchy'), ('crows', 'Corvid Conspiracy'), ('rats', 'Lord of the Hundreds'), ('badgers', 'Keepers in Iron')], default='', help_text='Select a preset background, or upload your own below.', max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='sheet_backgrounds/')),
                ('color', models.CharField(blank=True, help_text='Enter a hex color code (e.g., #RRGGBB).', max_length=7, null=True, validators=[the_keep.utils.validate_hex_color])),
                ('include_crafted_items', models.BooleanField(default=True)),
                ('repeat_background_image', models.BooleanField(default=False)),
                ('layout_mode', models.CharField(choices=[('auto', 'Layout Auto'), ('horizontal', 'Layout Horizontal'), ('vertical', 'Layout Vertical')], default='auto', max_length=30)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_sheets', to='the_gatehouse.profile')),
            ],
        ),
        migrations.AddField(
            model_name='decreesection',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decrees', to='the_forge.factionsheet'),
        ),
        migrations.AddField(
            model_name='cardboardtrack',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='the_forge.factionsheet'),
        ),
        migrations.CreateModel(
            name='PhaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('birdsong', 'Birdsong'), ('daylight', 'Daylight'), ('evening', 'Evening')], max_length=30)),
                ('number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_steps', to='the_forge.factionsheet')),
            ],
            options={
                'ordering': ['phase', 'number'],
            },
        ),
        migrations.CreateModel(
            name='SheetAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='the_forge.factionsheet')),
            ],
        ),
        migrations.CreateModel(
            name='StepSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='the_forge.phasestep')),
            ],
        ),
    ]
