# Generated by Django 5.1.13 on 2026-04-14 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_forge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardboardslot',
            name='row',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardboardslot',
            name='column',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardboardslot',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='forge/slot_backgrounds/'),
        ),
        migrations.AddField(
            model_name='cardboardslot',
            name='content',
            field=models.CharField(blank=True, default='', help_text='Pipe-delimited image keywords, e.g. "1VP" or "fox|1VP"', max_length=200),
        ),
        migrations.AddField(
            model_name='cardboardslot',
            name='row_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterModelOptions(
            name='cardboardslot',
            options={'ordering': ['row', 'column']},
        ),
        migrations.AlterUniqueTogether(
            name='cardboardslot',
            unique_together={('track', 'row', 'column')},
        ),
        migrations.AddField(
            model_name='cardboardtrack',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='forge/track_backgrounds/'),
        ),
        migrations.AddField(
            model_name='cardboardtrack',
            name='column_cost_type',
            field=models.CharField(blank=True, default='', help_text='Inline image keyword for column header icons, e.g. "VP"', max_length=20),
        ),
        migrations.AddField(
            model_name='cardboardtrack',
            name='column_dividers',
            field=models.CharField(blank=True, default='', help_text='Section dividers as "col:label" pairs, e.g. "2:1|5:2|7:3"', max_length=200),
        ),
        migrations.AddField(
            model_name='cardboardtrack',
            name='column_headers',
            field=models.CharField(blank=True, default='', help_text='Pipe-delimited column labels, e.g. "0|1|2|3|4"', max_length=500),
        ),
        migrations.AddField(
            model_name='cardboardtrack',
            name='num_columns',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cardboardslot',
            name='number',
            field=models.PositiveIntegerField(help_text='For admin ordering'),
        ),
        migrations.AlterField(
            model_name='factionsheet',
            name='layout_mode',
            field=models.CharField(choices=[('horizontal', 'Layout Horizontal'), ('vertical', 'Layout Vertical')], default='vertical', max_length=30),
        ),
        migrations.CreateModel(
            name='BorderedBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('height', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=15)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='the_forge.phasestep')),
            ],
        ),
        migrations.RemoveField(
            model_name='cardboardslot',
            name='title',
        ),
    ]
