# Generated by Django 5.1.13 on 2026-04-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_forge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepaction',
            name='cost',
            field=models.CharField(choices=[('action', 'Action'), ('item_sword', 'Sword'), ('item_hammer', 'Hammer'), ('item_crossbow', 'Crossbow'), ('item_coins', 'Coins'), ('item_boots', 'Boots'), ('item_tea', 'Tea'), ('item_bag', 'Bag'), ('item_torch', 'Torch'), ('item_any', 'Any Item'), ('card_fox', 'Fox'), ('card_mouse', 'Mouse'), ('card_rabbit', 'Rabbit'), ('card_bird', 'Bird'), ('card_nonbird', 'Non-Bird'), ('other', 'Other (Custom Image)')], default='action', max_length=20),
        ),
        migrations.AddField(
            model_name='stepaction',
            name='cost_image',
            field=models.ImageField(blank=True, null=True, upload_to='forge/cost_icons/'),
        ),
    ]
