# Generated by Django 5.1.13 on 2026-04-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_forge', '0002_alter_cardboardslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardboardtrack',
            name='header_position',
            field=models.CharField(choices=[('above', 'Above'), ('below', 'Below')], default='above', help_text='Display column headers above or below the slots', max_length=10),
        ),
    ]
