# Generated by Django 5.1.13 on 2026-04-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_forge', '0003_cardboardtrack_header_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardboardtrack',
            name='header_title',
            field=models.CharField(blank=True, default='', help_text='Title displayed in the row-title area of the header row', max_length=200),
        ),
        migrations.AlterField(
            model_name='cardboardtrack',
            name='column_dividers',
            field=models.CharField(blank=True, default='', help_text='Comma-separated column indices for dividers, e.g. "2,5,7"', max_length=200),
        ),
    ]
