# Generated by Django 5.1.13 on 2026-04-23 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_forge', '0004_cardboardtrack_header_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decreesection',
            name='type',
        ),
        migrations.AddField(
            model_name='cardboardtrack',
            name='row_title_orientation',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', help_text='Display row titles horizontally (default) or vertically (rotated 90°)', max_length=12),
        ),
        migrations.CreateModel(
            name='CardPile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_piles', to='the_forge.factionsheet')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
