from django.urls import path
# from .views import
from .views import (game_list_view, leaderboard_view,
                    game_detail_view,
                    game_add_extra_round, game_remove_extra_round,
                    game_delete_view, effort_hx_delete, game_hx_delete,
                    bookmark_game, manage_game,
                    manage_game_v2, about_series_view, about_games_view,
                    scorecard_detail_view,
                    scorecard_assign_view, scorecard_delete_view, scorecard_list_view, effort_assign_view,
                    scorecard_manage_view,
                    tournament_overview_page, round_overview_page,
                    set_view_as,
                    TournamentDeleteView, tournaments_home,
                    tournament_dynamic_create, tournament_dynamic_update,
                    tournament_search_players, tournament_move_player, search_moderators,
                    tournament_search_assets, tournament_add_asset, tournament_remove_asset,
                    tournament_manage_players, tournament_manage_assets,
                    tournament_settings_hub, round_settings_hub,
                    round_manage_view,
                    round_manage_players, round_search_players, round_move_player, RoundDeleteView,
                    round_games_pagination,
                    in_progress_view, tournament_component_leaderboard, tournament_player_leaderboard,
                    add_player_to_effort, my_submitted_games_view,
                    # Round grouping views
                    round_grouping_setup_view, round_grouping_status, round_grouping_reset,
                    round_grouping_move_player, round_grouping_add_to_group,
                    round_grouping_remove_from_group, round_grouping_create_group,
                    round_grouping_delete_group,
                    round_grouping_edit_group,
                    round_grouping_finalize,
                    round_generate_bracket, round_finalize_bracket, round_enable_matches, round_edit_series, round_create_series, round_delete_series,
                    tournament_bracket_page,
                    stage_manage_view, stage_overview_page, stage_settings_hub, StageDeleteView,
                    stage_manage_players, stage_search_players, stage_move_player,
                    stage_leaderboard_page, stage_games_page, stage_roster_page,
                    stage_details_page, stage_bracket_page, stage_matches_page,
                    stage_grouping_setup_view,
                    stage_advancement_page, stage_advancement_submit, stage_create_quick,
                    stage_advancement_config, tournament_enable_stages, stage_enable_rounds,
                    tournament_disable_stages, stage_disable_rounds,
                    tournament_leaderboard_page, tournament_games_page,
                    tournament_roster_page, tournament_details_page,
                    round_leaderboard_page, round_games_page,
                    round_roster_page, round_details_page, round_matches_page,
                    tournament_schedule_page, stage_schedule_page, round_schedule_page)

urlpatterns = [
    path('record/game/', manage_game, name='record-game'),
    path('record/game/v2/', manage_game_v2, name='record-game-v2'),
    path("game/<int:id>/edit/v2/", manage_game_v2, name='game-update-v2'),
    path("rootleague/match/<int:league_id>/", game_detail_view, name='rdl-game-detail'),
    path("game/<int:id>/delete/", game_delete_view, name='game-delete'),
    path("game/<int:id>/extra-round/add/", game_add_extra_round, name='game-add-extra-round'),
    path("game/<int:id>/extra-round/<int:round_id>/remove/", game_remove_extra_round, name='game-remove-extra-round'),
    path("game/<int:id>/edit/", manage_game, name='game-update'),
    path("game/<int:id>/", game_detail_view, name='game-detail'),
    

    path('battlefield/active/', in_progress_view, name='in-progress'),
    path('battlefield/my-games/', my_submitted_games_view, name='my-submitted-games'),
    path('battlefield/', game_list_view, name='games-home'),
    path('warroom/', game_list_view),
    path('games/', game_list_view),

    path('leaderboard/', leaderboard_view, name='leaderboard-view'),

    path('record/scorecard/', scorecard_manage_view, name='record-scorecard'),
    path("scorecard/<int:id>/edit/", scorecard_manage_view, name='update-scorecard'),
    # path('record/old-scorecard/', scorecard_old_manage_view, name='record-old-scorecard'),
    path("scorecard/<int:id>/", scorecard_detail_view, name='detail-scorecard'),
    # path("scorecard/<int:id>/old-edit", scorecard_old_manage_view, name='update-old-scorecard'),
    path("scorecard/<int:id>/delete", scorecard_delete_view, name='delete-scorecard'),
    path('scorecard/assign/<int:id>/', scorecard_assign_view, name='assign-scorecard'),
    path('scorecard/<int:id>/assign/', effort_assign_view, name='assign-effort'),
    path('scorecards/', scorecard_list_view, name='scorecard-home'),

    # Tournaments
    path('new/series/', tournament_dynamic_create, name='tournament-dynamic-create'),
    path('series/<slug:slug>/update/', tournament_dynamic_update, name='tournament-dynamic-update'),

    # HTMX endpoints for player management
    path('series/<slug:slug>/players/search/', tournament_search_players, name='tournament-search-players'),
    path('series/<slug:slug>/players/move/', tournament_move_player, name='tournament-move-player'),
    path('moderators/search/', search_moderators, name='search-moderators'),

    # HTMX endpoints for asset management
    path('series/<slug:slug>/assets/<str:asset_type>/search/', tournament_search_assets, name='tournament-search-assets'),
    path('series/<slug:slug>/assets/<str:asset_type>/<int:asset_id>/add/', tournament_add_asset, name='tournament-add-asset'),
    path('series/<slug:slug>/assets/<str:asset_type>/<int:asset_id>/remove/', tournament_remove_asset, name='tournament-remove-asset'),
    
    path('series/<slug:slug>/view-as/', set_view_as, name='tournament-view-as'),

    path('series/<slug:slug>/bracket/', tournament_bracket_page, name='tournament-bracket-page'),
    path('series/<slug:slug>/schedule/', tournament_schedule_page, name='tournament-schedule-page'),
    path('series/<slug:slug>/leaderboard/', tournament_leaderboard_page, name='tournament-leaderboard-page'),
    path('series/<slug:tournament_slug>/component/<slug:post_slug>/', tournament_component_leaderboard, name='tournament-component-leaderboard'),
    path('series/<slug:tournament_slug>/player/<slug:profile_slug>/', tournament_player_leaderboard, name='tournament-player-leaderboard'),
    path('series/<slug:slug>/games/', tournament_games_page, name='tournament-games-page'),
    path('series/<slug:slug>/roster/', tournament_roster_page, name='tournament-roster-page'),
    path('series/<slug:slug>/details/', tournament_details_page, name='tournament-details-page'),
    path('series/<slug:slug>/settings/', tournament_settings_hub, name='tournament-settings'),
    path('series/<slug:slug>/players/', tournament_manage_players, name='tournament-manage-players'),
    path('series/<slug:slug>/assets/', tournament_manage_assets, name='tournament-manage-assets'),

    path('series/<slug:slug>/', tournament_overview_page, name='tournament-detail'),
    path('series/<slug:slug>/delete/', TournamentDeleteView.as_view(), name='tournament-delete'),

    path('hx/round/<int:id>/game-list/', round_games_pagination, name='round-games-pagination'),
    path('add-player-to-effort/', add_player_to_effort, name='add-player-to-effort'),

    # Stages
    path('series/<slug:tournament_slug>/stage-create-quick/', stage_create_quick, name='stage-create-quick'),
    path('series/<slug:tournament_slug>/enable-stages/', tournament_enable_stages, name='tournament-enable-stages'),
    path('series/<slug:tournament_slug>/disable-stages/', tournament_disable_stages, name='tournament-disable-stages'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/enable-rounds/', stage_enable_rounds, name='stage-enable-rounds'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/disable-rounds/', stage_disable_rounds, name='stage-disable-rounds'),
    path('series/<slug:tournament_slug>/stage/new/', stage_manage_view, name='stage-create'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/update/', stage_manage_view, name='stage-update'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/settings/', stage_settings_hub, name='stage-settings'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/players/', stage_manage_players, name='stage-manage-players'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/players/search/', stage_search_players, name='stage-search-players'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/players/move/', stage_move_player, name='stage-move-player'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/leaderboard/', stage_leaderboard_page, name='stage-leaderboard-page'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/component/<slug:post_slug>/', tournament_component_leaderboard, name='stage-component-leaderboard'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/player/<slug:profile_slug>/', tournament_player_leaderboard, name='stage-player-leaderboard'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/games/', stage_games_page, name='stage-games-page'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/roster/', stage_roster_page, name='stage-roster-page'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/details/', stage_details_page, name='stage-details-page'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/bracket/', stage_bracket_page, name='stage-bracket-page'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/matches/', stage_matches_page, name='stage-matches-page'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/schedule/', stage_schedule_page, name='stage-schedule-page'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/grouping/', stage_grouping_setup_view, name='stage-grouping-setup'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/delete/', StageDeleteView.as_view(), name='stage-delete'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/advancement/', stage_advancement_page, name='stage-advancement-page'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/advancement/submit/', stage_advancement_submit, name='stage-advancement-submit'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/advancement/config/', stage_advancement_config, name='stage-advancement-config'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/', stage_overview_page, name='stage-overview'),

    # Rounds - Simplified URLs (no stage_slug) for tournaments with use_stages=False
    path('series/<slug:tournament_slug>/new/round/', round_manage_view, name='round-create-simple'),
    path('series/<slug:tournament_slug>/round/<slug:round_slug>/', round_overview_page, name='round-overview-simple'),
    path('series/<slug:tournament_slug>/round/<slug:round_slug>/leaderboard/', round_leaderboard_page, name='round-leaderboard-simple'),
    path('series/<slug:tournament_slug>/round/<slug:round_slug>/component/<slug:post_slug>/', tournament_component_leaderboard, name='round-component-leaderboard-simple'),
    path('series/<slug:tournament_slug>/round/<slug:round_slug>/player/<slug:profile_slug>/', tournament_player_leaderboard, name='round-player-leaderboard-simple'),
    path('series/<slug:tournament_slug>/round/<slug:round_slug>/games/', round_games_page, name='round-games-simple'),
    path('series/<slug:tournament_slug>/round/<slug:round_slug>/roster/', round_roster_page, name='round-roster-simple'),
    path('series/<slug:tournament_slug>/round/<slug:round_slug>/details/', round_details_page, name='round-details-simple'),
    path('series/<slug:tournament_slug>/round/<slug:round_slug>/matches/', round_matches_page, name='round-matches-simple'),
    path('series/<slug:tournament_slug>/round/<slug:round_slug>/schedule/', round_schedule_page, name='round-schedule-simple'),
    path('series/<slug:tournament_slug>/round/<slug:round_slug>/settings/', round_settings_hub, name='round-settings-simple'),
    path('series/<slug:tournament_slug>/round/<slug:round_slug>/players/', round_manage_players, name='round-manage-players-simple'),
    path('series/<slug:tournament_slug>/round/<slug:round_slug>/update/', round_manage_view, name='round-update-simple'),
    path('series/<slug:tournament_slug>/round/<slug:round_slug>/delete/<int:pk>/', RoundDeleteView.as_view(), name='round-delete-simple'),
    path('series/<slug:tournament_slug>/round/<slug:round_slug>/grouping/', round_grouping_setup_view, name='round-grouping-setup-simple'),

    # Rounds - Full URLs (with stage_slug) for all tournaments
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/new/round/', round_manage_view, name='round-create'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/', round_overview_page, name='round-overview'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/leaderboard/', round_leaderboard_page, name='round-leaderboard-page'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/component/<slug:post_slug>/', tournament_component_leaderboard, name='round-component-leaderboard'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/player/<slug:profile_slug>/', tournament_player_leaderboard, name='round-player-leaderboard'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/games/', round_games_page, name='round-games-page'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/roster/', round_roster_page, name='round-roster-page'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/details/', round_details_page, name='round-details-page'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/matches/', round_matches_page, name='round-matches-page'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/schedule/', round_schedule_page, name='round-schedule-page'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/settings/', round_settings_hub, name='round-settings'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/players/', round_manage_players, name='round-manage-players'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/update/', round_manage_view, name='round-update'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/delete/<int:pk>/', RoundDeleteView.as_view(), name='round-delete'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/grouping/', round_grouping_setup_view, name='round-grouping-setup'),

    # Round HTMX & AJAX
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/players/search/', round_search_players, name='round-search-players'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/players/move/', round_move_player, name='round-move-player'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/grouping/<int:session_id>/status/', round_grouping_status, name='round-grouping-status'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/grouping/<int:session_id>/reset/', round_grouping_reset, name='round-grouping-reset'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/grouping/<int:session_id>/move-player/', round_grouping_move_player, name='round-grouping-move-player'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/grouping/<int:session_id>/add-to-group/', round_grouping_add_to_group, name='round-grouping-add-to-group'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/grouping/<int:session_id>/remove-from-group/', round_grouping_remove_from_group, name='round-grouping-remove-from-group'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/grouping/<int:session_id>/create-group/', round_grouping_create_group, name='round-grouping-create-group'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/grouping/<int:session_id>/delete-group/', round_grouping_delete_group, name='round-grouping-delete-group'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/grouping/<int:session_id>/edit-group/', round_grouping_edit_group, name='round-grouping-edit-group'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/grouping/<int:session_id>/finalize/', round_grouping_finalize, name='round-grouping-finalize'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/generate-bracket/', round_generate_bracket, name='round-generate-bracket'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/finalize-bracket/', round_finalize_bracket, name='round-finalize-bracket'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/enable-matches/', round_enable_matches, name='round-enable-matches'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/edit-series/', round_edit_series, name='round-edit-series'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/create-series/', round_create_series, name='round-create-series'),
    path('series/<slug:tournament_slug>/stage/<slug:stage_slug>/round/<slug:round_slug>/delete-series/', round_delete_series, name='round-delete-series'),


    path('about/series/', about_series_view, name='about-series'),
    path('about/games/', about_games_view, name='about-games'),
    path('series/', tournaments_home, name='tournaments-home'),

    path("hx/games/<int:id>/bookmark/", bookmark_game, name='bookmark-game'),
    path("hx/games/effort/delete/<int:id>/", effort_hx_delete, name='effort-hx-delete'),
    path("hx/games/game/delete/<int:id>/", game_hx_delete, name='game-hx-delete'),

]
