# Generated by Django 5.1.2 on 2024-12-09 22:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_images/default_user.png', upload_to='profile_pics')),
                ('dwd', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('discord', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('league', models.BooleanField(default=False)),
                ('group', models.CharField(choices=[('O', 'Outcast'), ('P', 'Player'), ('D', 'Designer'), ('A', 'Admin'), ('B', 'Banned')], default='O', max_length=1)),
                ('weird', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('bookmarks', models.ManyToManyField(through='the_gatehouse.PlayerBookmark', to='the_gatehouse.profile')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='playerbookmark',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='the_gatehouse.profile'),
        ),
        migrations.AddField(
            model_name='playerbookmark',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_gatehouse.profile'),
        ),
    ]
