# Generated by Django 5.1.2 on 2024-10-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gatehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='creative',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
