# Generated by Django 5.1.2 on 2024-11-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gatehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.CharField(choices=[('O', 'Outcast'), ('P', 'Player'), ('D', 'Designer'), ('A', 'Admin')], default='O', max_length=1),
        ),
    ]
