# Generated by Django 5.1.2 on 2024-11-18 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_gatehouse', '0002_profile_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='creative',
        ),
    ]
