# Generated by Django 5.1.2 on 2024-11-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gatehouse', '0002_profile_creative_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='creative',
            field=models.BooleanField(default=False),
        ),
    ]
