# Generated by Django 5.1.2 on 2024-11-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gatehouse', '0003_remove_profile_creative'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weird',
            field=models.BooleanField(default=False),
        ),
    ]
