# Generated by Django 5.1.2 on 2024-11-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gatehouse', '0004_profile_weird'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.CharField(choices=[('O', 'Outcast'), ('P', 'Player'), ('D', 'Designer'), ('A', 'Admin'), ('B', 'Banned')], default='O', max_length=1),
        ),
    ]
