# Generated by Django 5.1.2 on 2024-11-20 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gatehouse', '0005_alter_profile_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='the_gatehouse.profile')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_gatehouse.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='playerbookmarks',
            field=models.ManyToManyField(through='the_gatehouse.PlayerBookmark', to='the_gatehouse.profile'),
        ),
    ]
