# Generated by Django 5.1.2 on 2024-11-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_gatehouse', '0006_playerbookmark_profile_playerbookmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='playerbookmarks',
            new_name='bookmarks',
        ),
    ]
