# Generated by Django 5.1.2 on 2024-11-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_tavern', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='profile',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='profile',
            new_name='player',
        ),
    ]
