# Generated by Django 5.1.2 on 2024-11-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_tavern', '0002_rename_profile_bookmark_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
