# Generated by Django 5.1.2 on 2024-11-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_tavern', '0003_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='private',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='private',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
