# Generated by Django 5.1.2 on 2024-11-19 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_tavern', '0004_remove_bookmark_private_remove_comment_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
