# Generated by Django 5.1.2 on 2024-11-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_tavern', '0006_remove_comment_game_remove_comment_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecomment',
            name='body',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='body',
            field=models.CharField(max_length=300),
        ),
    ]
