# Generated by Django 5.1.2 on 2024-11-19 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_keep', '0001_initial'),
        ('the_tavern', '0007_alter_gamecomment_body_alter_postcomment_body'),
        ('the_warroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebookmark',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='the_warroom.game'),
        ),
        migrations.AlterField(
            model_name='gamecomment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='the_warroom.game'),
        ),
        migrations.AlterField(
            model_name='postbookmark',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='the_keep.post'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='the_keep.post'),
        ),
    ]
