# Generated by Django 5.1.2 on 2024-11-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_tavern', '0008_alter_gamebookmark_game_alter_gamecomment_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerbookmark',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='playerbookmark',
            name='player',
        ),
        migrations.RemoveField(
            model_name='postbookmark',
            name='player',
        ),
        migrations.RemoveField(
            model_name='postbookmark',
            name='post',
        ),
        migrations.DeleteModel(
            name='GameBookmark',
        ),
        migrations.DeleteModel(
            name='PlayerBookmark',
        ),
        migrations.DeleteModel(
            name='PostBookmark',
        ),
    ]
