# Generated by Django 5.1.2 on 2024-11-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_tavern', '0009_remove_playerbookmark_friend_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecomment',
            options={'ordering': ['-date_posted']},
        ),
    ]
