# Generated by Django 5.1.2 on 2024-10-29 23:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('the_gatehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Async'), ('L', 'Live')], default='L', max_length=1)),
                ('platform', models.CharField(choices=[('TTS', 'Tabletop Simulator'), ('IRL', 'In Person'), ('DWD', 'Root Digital'), ('HRF', 'hrf.com'), ('ETC', 'Other')], default='DWD', max_length=3)),
                ('league', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('random_clearing', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.deck')),
                ('hirelings', models.ManyToManyField(blank=True, to='blog.hireling')),
                ('landmarks', models.ManyToManyField(blank=True, to='blog.landmark')),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.map')),
                ('recorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_gatehouse.profile')),
                ('undrafted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.faction')),
            ],
        ),
        migrations.CreateModel(
            name='Effort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('dominance', models.BooleanField(default=False)),
                ('clockwork', models.BooleanField(default=False)),
                ('win', models.BooleanField()),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('faction_status', models.CharField(blank=True, max_length=15, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('coalition_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coalition_with', to='blog.faction')),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.faction')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_gatehouse.profile')),
                ('vagabond', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.vagabond')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='the_warroom.game')),
            ],
        ),
    ]
