# Generated by Django 5.1.2 on 2024-11-07 00:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('the_gatehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Async', 'A'), ('Live', 'L')], default='Live', max_length=5)),
                ('platform', models.CharField(choices=[('Tabletop Simulator', 'TTS'), ('In Person', 'IRL'), ('Root Digital', 'DWD'), ('hrf.com', 'HRF'), ('Other', 'ETC')], default='Root Digital', max_length=20)),
                ('league', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('random_clearing', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('deck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.deck')),
                ('hirelings', models.ManyToManyField(blank=True, to='blog.hireling')),
                ('landmarks', models.ManyToManyField(blank=True, to='blog.landmark')),
                ('map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.map')),
                ('recorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_gatehouse.profile')),
                ('undrafted_faction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.faction')),
                ('undrafted_vagabond', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.vagabond')),
            ],
        ),
        migrations.CreateModel(
            name='Effort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('dominance', models.BooleanField(default=False)),
                ('clockwork', models.BooleanField(default=False)),
                ('win', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('faction_status', models.CharField(blank=True, max_length=15, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('captains', models.ManyToManyField(blank=True, related_name='as_captain', to='blog.vagabond')),
                ('coalition_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coalition_with', to='blog.faction')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.faction')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='the_gatehouse.profile')),
                ('vagabond', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.vagabond')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_warroom.game')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('participants', models.ManyToManyField(blank=True, to='the_gatehouse.profile')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_warroom.tournament'),
        ),
    ]
