# Generated by Django 5.1.2 on 2024-12-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='total_battle_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='total_crafting_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='total_faction_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='total_other_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='total_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
