# Generated by Django 5.1.2 on 2024-11-13 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gatehouse', '0001_initial'),
        ('the_warroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effort',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efforts', to='the_warroom.game'),
        ),
        migrations.AlterField(
            model_name='effort',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='efforts', to='the_gatehouse.profile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('Tabletop Simulator', 'Tts'), ('hrf.com', 'Hrf'), ('Root Digital', 'Dwd'), ('In Person', 'Irl'), ('Other', 'Etc')], default='Root Digital', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('Async', 'Async'), ('Live', 'Live')], default='Async', max_length=5),
        ),
    ]
