# Generated by Django 5.1.2 on 2024-12-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='test_match',
            field=models.BooleanField(default=False),
        ),
    ]
