# Generated by Django 5.1.2 on 2024-10-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('Tabletop Simulator', 'TTS'), ('In Person', 'IRL'), ('Root Digital', 'DWD'), ('hrf.com', 'HRF'), ('Other', 'ETC')], default='Root Digital', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('Async', 'A'), ('Live', 'L')], default='Live', max_length=5),
        ),
    ]
