# Generated by Django 5.1.2 on 2024-11-20 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gatehouse', '0006_playerbookmark_profile_playerbookmarks'),
        ('the_warroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_warroom.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_gatehouse.profile')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarkedgames', through='the_warroom.GameBookmark', to='the_gatehouse.profile'),
        ),
    ]
