# Generated by Django 5.1.2 on 2024-11-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_faction_type'),
        ('the_warroom', '0002_alter_effort_game_alter_effort_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effort',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='efforts', to='blog.faction'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('Tabletop Simulator', 'Tts'), ('Root Digital', 'Dwd'), ('In Person', 'Irl')], default='Root Digital', max_length=20),
        ),
    ]
