# Generated by Django 5.1.2 on 2024-12-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0002_game_test_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnscore',
            name='dominance',
            field=models.BooleanField(default=False),
        ),
    ]
