# Generated by Django 5.1.2 on 2024-10-29 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_component'),
        ('the_warroom', '0002_effort_date_posted_game_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effort',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.faction'),
        ),
    ]
