# Generated by Django 5.1.2 on 2024-10-30 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0002_alter_game_platform_alter_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effort',
            name='score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='effort',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
