# Generated by Django 5.1.2 on 2024-11-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0002_gamebookmark_game_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effort',
            name='notes',
        ),
    ]
