# Generated by Django 5.1.2 on 2024-12-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0002_scorecard_total_battle_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='total_battle_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='total_crafting_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='total_faction_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='total_other_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
