# Generated by Django 5.1.2 on 2024-10-30 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gatehouse', '0001_initial'),
        ('the_warroom', '0003_alter_effort_score_alter_effort_win'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('participants', models.ManyToManyField(blank=True, null=True, to='the_gatehouse.profile')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_warroom.tournament'),
        ),
    ]
