# Generated by Django 5.1.2 on 2024-12-07 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0003_alter_scorecard_total_battle_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='effort',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorecard', to='the_warroom.effort'),
        ),
    ]
