# Generated by Django 5.1.2 on 2024-11-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0003_remove_effort_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effort',
            name='faction_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('Async', 'Async'), ('Live', 'Live')], default='Live', max_length=5),
        ),
    ]
