# Generated by Django 5.1.2 on 2024-11-15 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_map_default_landmark_alter_post_designer'),
        ('the_warroom', '0003_alter_effort_faction_alter_game_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterField(
            model_name='effort',
            name='vagabond',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='efforts', to='blog.vagabond'),
        ),
    ]
