# Generated by Django 5.1.2 on 2024-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0003_turnscore_dominance'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='coalition_win',
            field=models.BooleanField(default=False),
        ),
    ]
