# Generated by Django 5.1.2 on 2024-12-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0004_alter_effort_faction_status_alter_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('Tabletop Simulator', 'Tts'), ('Root Digital', 'Dwd'), ('In Person', 'Irl')], default='Tabletop Simulator', max_length=20),
        ),
    ]
