# Generated by Django 5.1.2 on 2024-10-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gatehouse', '0001_initial'),
        ('the_warroom', '0004_tournament_game_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(blank=True, to='the_gatehouse.profile'),
        ),
    ]
