# Generated by Django 5.1.2 on 2024-11-16 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_deck_card_back_remove_faction_faction_board_and_more'),
        ('the_gatehouse', '0003_alter_profile_image'),
        ('the_warroom', '0004_alter_game_options_alter_effort_vagabond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effort',
            name='captains',
            field=models.ManyToManyField(blank=True, related_name='efforts_as_captain', to='blog.vagabond'),
        ),
        migrations.AlterField(
            model_name='effort',
            name='coalition_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='efforts_in_coalition', to='blog.faction'),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='blog.deck'),
        ),
        migrations.AlterField(
            model_name='game',
            name='hirelings',
            field=models.ManyToManyField(blank=True, related_name='games', to='blog.hireling'),
        ),
        migrations.AlterField(
            model_name='game',
            name='landmarks',
            field=models.ManyToManyField(blank=True, related_name='games', to='blog.landmark'),
        ),
        migrations.AlterField(
            model_name='game',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='blog.map'),
        ),
        migrations.AlterField(
            model_name='game',
            name='recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_recorded', to='the_gatehouse.profile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='undrafted_faction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='undrafted_games', to='blog.faction'),
        ),
        migrations.AlterField(
            model_name='game',
            name='undrafted_vagabond',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='undrafted_games', to='blog.vagabond'),
        ),
    ]
