# Generated by Django 5.1.2 on 2024-12-02 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_keep', '0005_alter_expansion_designer'),
        ('the_warroom', '0005_alter_game_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games', to='the_keep.deck'),
        ),
        migrations.AlterField(
            model_name='game',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games', to='the_keep.map'),
        ),
    ]
