# Generated by Django 5.1.2 on 2024-10-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0005_alter_tournament_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
