# Generated by Django 5.1.2 on 2024-10-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0006_alter_game_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
