# Generated by Django 5.1.2 on 2024-12-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0006_alter_game_deck_alter_game_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effort',
            name='dominance',
        ),
        migrations.AddField(
            model_name='effort',
            name='dominance_type',
            field=models.CharField(blank=True, choices=[('Mouse', 'Mouse'), ('Fox', 'Fox'), ('Rabbit', 'Rabbit'), ('Bird', 'Bird'), ('Dark', 'Dark')], max_length=10, null=True),
        ),
    ]
