# Generated by Django 5.1.2 on 2024-12-04 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0007_remove_effort_dominance_effort_dominance_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='effort',
            old_name='dominance_type',
            new_name='dominance',
        ),
    ]
