# Generated by Django 5.1.2 on 2024-11-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0008_tournament_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effort',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_warroom.game'),
        ),
    ]
