# Generated by Django 5.1.2 on 2024-12-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0008_rename_dominance_type_effort_dominance'),
    ]

    operations = [
        migrations.AddField(
            model_name='effort',
            name='player_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
