# Generated by Django 5.1.2 on 2024-11-02 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_faction_win_icon'),
        ('the_warroom', '0009_alter_effort_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.deck'),
        ),
        migrations.AlterField(
            model_name='game',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.map'),
        ),
    ]
