# Generated by Django 5.1.2 on 2024-12-04 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0009_effort_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effort',
            name='player_name',
        ),
    ]
