# Generated by Django 5.1.2 on 2024-11-03 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_faction_win_icon'),
        ('the_gatehouse', '0003_alter_profile_creative'),
        ('the_warroom', '0010_alter_game_deck_alter_game_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effort',
            name='coalition_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coalition_with', to='blog.faction'),
        ),
        migrations.AlterField(
            model_name='effort',
            name='faction',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='blog.faction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='effort',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='the_gatehouse.profile'),
        ),
        migrations.AlterField(
            model_name='effort',
            name='vagabond',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.vagabond'),
        ),
    ]
