# Generated by Django 5.1.2 on 2024-12-06 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gatehouse', '0007_rename_playerbookmarks_profile_bookmarks'),
        ('the_keep', '0008_alter_post_options'),
        ('the_warroom', '0010_remove_effort_player_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='effort',
            options={'ordering': ['game', 'seat']},
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('effort', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='the_warroom.effort')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_score', to='the_keep.faction')),
                ('recorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_gatehouse.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TurnScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField(default=0)),
                ('battle_points', models.IntegerField(default=0)),
                ('crafting_points', models.IntegerField(default=0)),
                ('faction_points', models.IntegerField(default=0)),
                ('other_points', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('game_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='the_warroom.gamescore')),
            ],
            options={
                'unique_together': {('game_score', 'turn_number')},
            },
        ),
    ]
