# Generated by Django 5.1.2 on 2024-12-06 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0011_alter_effort_options_gamescore_turnscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
