# Generated by Django 5.1.2 on 2024-11-04 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_faction_win_icon'),
        ('the_warroom', '0011_alter_effort_coalition_with_alter_effort_faction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='vagabond',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.vagabond'),
        ),
        migrations.AlterField(
            model_name='game',
            name='undrafted',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.faction'),
        ),
    ]
