# Generated by Django 5.1.2 on 2024-11-04 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_warroom', '0012_game_vagabond_alter_game_undrafted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='undrafted',
            new_name='undrafted_faction',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='vagabond',
            new_name='undrafted_vagabond',
        ),
    ]
