# Generated by Django 5.1.2 on 2024-12-06 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_gatehouse', '0007_rename_playerbookmarks_profile_bookmarks'),
        ('the_keep', '0008_alter_post_options'),
        ('the_warroom', '0012_gamescore_date_posted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameScore',
            new_name='ScoreCard',
        ),
    ]
