# Generated by Django 5.1.2 on 2024-11-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_artist_profile_post_designer_profile'),
        ('the_warroom', '0013_rename_undrafted_game_undrafted_faction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='effort',
            name='captains',
            field=models.ManyToManyField(blank=True, related_name='as_captain', to='blog.vagabond'),
        ),
    ]
