# Generated by Django 5.1.2 on 2024-12-06 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_keep', '0008_alter_post_options'),
        ('the_warroom', '0013_rename_gamescore_scorecard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnscore',
            options={'ordering': ['turn_number']},
        ),
        migrations.RenameField(
            model_name='turnscore',
            old_name='game_score',
            new_name='scorecard',
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='the_keep.faction'),
        ),
        migrations.AlterUniqueTogether(
            name='turnscore',
            unique_together={('scorecard', 'turn_number')},
        ),
    ]
