# Generated by Django 5.1.2 on 2024-11-11 21:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('the_gatehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('lore', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('official', models.BooleanField(default=False)),
                ('stable', models.BooleanField(default=False)),
                ('bgg_link', models.CharField(blank=True, max_length=200, null=True)),
                ('tts_link', models.CharField(blank=True, max_length=200, null=True)),
                ('ww_link', models.CharField(blank=True, max_length=200, null=True)),
                ('wr_link', models.CharField(blank=True, max_length=200, null=True)),
                ('pnp_link', models.CharField(blank=True, max_length=200, null=True)),
                ('change_log', models.TextField(default='[]')),
                ('component', models.CharField(blank=True, choices=[('Map', 'Map'), ('Deck', 'Deck'), ('Hireling', 'Hireling'), ('Vagabond', 'Vagabond'), ('Landmark', 'Landmark'), ('Faction', 'Faction')], max_length=10, null=True)),
                ('small_icon', models.ImageField(blank=True, null=True, upload_to='small_component_icons')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='component_pictures')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_posts', to='the_gatehouse.profile')),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post')),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_gatehouse.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_gatehouse.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('card_total', models.IntegerField()),
            ],
            bases=('blog.post',),
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('animal', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('M', 'Militant'), ('I', 'Insurgent')], max_length=1)),
                ('reach', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('complexity', models.CharField(choices=[('N', 'N'), ('L', 'L'), ('M', 'M'), ('H', 'H')], max_length=1)),
                ('card_wealth', models.CharField(choices=[('N', 'N'), ('L', 'L'), ('M', 'M'), ('H', 'H')], max_length=1)),
                ('aggression', models.CharField(choices=[('N', 'N'), ('L', 'L'), ('M', 'M'), ('H', 'H')], max_length=1)),
                ('crafting_ability', models.CharField(choices=[('N', 'N'), ('L', 'L'), ('M', 'M'), ('H', 'H')], max_length=1)),
                ('adset_card', models.ImageField(blank=True, default=None, null=True, upload_to='adset_cards')),
                ('clockwork', models.BooleanField(default=False)),
            ],
            bases=('blog.post',),
        ),
        migrations.CreateModel(
            name='Hireling',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('animal', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('P', 'Promoted'), ('D', 'Demoted')], max_length=1)),
            ],
            bases=('blog.post',),
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('card_text', models.TextField()),
            ],
            bases=('blog.post',),
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post')),
                ('clearings', models.IntegerField(default=12)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            bases=('blog.post',),
        ),
        migrations.CreateModel(
            name='Vagabond',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('animal', models.CharField(max_length=15)),
                ('ability_item', models.CharField(blank=True, max_length=150, null=True)),
                ('ability', models.CharField(max_length=150)),
                ('ability_description', models.TextField(blank=True, null=True)),
                ('starting_coins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('starting_boots', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('starting_bag', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('starting_tea', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('starting_hammer', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('starting_crossbow', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('starting_torch', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
            ],
            bases=('blog.post',),
        ),
        migrations.AddField(
            model_name='post',
            name='expansion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.expansion'),
        ),
        migrations.CreateModel(
            name='Warrior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('description', models.TextField(blank=True, null=True)),
                ('suited', models.BooleanField(default=False)),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='blog.faction')),
                ('hireling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='blog.hireling')),
                ('vagabond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='blog.vagabond')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('description', models.TextField(blank=True, null=True)),
                ('suited', models.BooleanField(default=False)),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='blog.faction')),
                ('hireling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='blog.hireling')),
                ('vagabond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='blog.vagabond')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('description', models.TextField(blank=True, null=True)),
                ('suited', models.BooleanField(default=False)),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='blog.faction')),
                ('hireling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='blog.hireling')),
                ('vagabond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='blog.vagabond')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('description', models.TextField(blank=True, null=True)),
                ('suited', models.BooleanField(default=False)),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='blog.faction')),
                ('hireling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='blog.hireling')),
                ('vagabond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='blog.vagabond')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('description', models.TextField(blank=True, null=True)),
                ('suited', models.BooleanField(default=False)),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='blog.faction')),
                ('hireling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='blog.hireling')),
                ('vagabond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='blog.vagabond')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
