# Generated by Django 5.1.2 on 2024-10-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lore',
            field=models.TextField(blank=True, null=True),
        ),
    ]
