# Generated by Django 5.1.2 on 2024-10-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_lore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expansion',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='expansion',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
