# Generated by Django 5.1.2 on 2024-10-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_name_expansion_title_expansion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='faction_icon',
            field=models.ImageField(default='default_icon.png', upload_to='faction_icons'),
        ),
    ]
