# Generated by Django 5.1.2 on 2024-10-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='component',
            field=models.CharField(blank=True, choices=[('Map', 'Map'), ('Deck', 'Deck'), ('Hireling', 'Hireling'), ('Vagabond', 'Vagabond'), ('Landmark', 'Landmark'), ('Faction', 'Faction')], max_length=10, null=True),
        ),
    ]
