# Generated by Django 5.1.2 on 2024-12-09 22:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('the_gatehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('lore', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('official', models.BooleanField(default=False)),
                ('in_root_digital', models.BooleanField(default=False)),
                ('stable', models.BooleanField(default=False)),
                ('bgg_link', models.CharField(blank=True, max_length=200, null=True)),
                ('tts_link', models.CharField(blank=True, max_length=200, null=True)),
                ('ww_link', models.CharField(blank=True, max_length=200, null=True)),
                ('wr_link', models.CharField(blank=True, max_length=200, null=True)),
                ('pnp_link', models.CharField(blank=True, max_length=200, null=True)),
                ('change_log', models.TextField(default='[]')),
                ('component', models.CharField(blank=True, choices=[('Map', 'Map'), ('Deck', 'Deck'), ('Hireling', 'Hireling'), ('Vagabond', 'Vagabond'), ('Landmark', 'Landmark'), ('Faction', 'Faction')], max_length=10, null=True)),
                ('small_icon', models.ImageField(blank=True, null=True, upload_to='small_component_icons/custom')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='component_pictures')),
                ('board_image', models.ImageField(blank=True, null=True, upload_to='boards')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='cards')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_posts', to='the_gatehouse.profile')),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_keep.post')),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='the_gatehouse.profile')),
            ],
            options={
                'ordering': ['-official', '-stable', '-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('lore', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_gatehouse.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='the_keep.post')),
                ('card_total', models.IntegerField()),
            ],
            bases=('the_keep.post',),
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='the_keep.post')),
                ('animal', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('M', 'Militant'), ('I', 'Insurgent')], max_length=10)),
                ('reach', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('complexity', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Moderate'), ('H', 'High')], max_length=1)),
                ('card_wealth', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Moderate'), ('H', 'High')], max_length=1)),
                ('aggression', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Moderate'), ('H', 'High')], max_length=1)),
                ('crafting_ability', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Moderate'), ('H', 'High')], max_length=1)),
                ('clockwork', models.BooleanField(default=False)),
            ],
            bases=('the_keep.post',),
        ),
        migrations.CreateModel(
            name='Hireling',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='the_keep.post')),
                ('animal', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('P', 'Promoted'), ('D', 'Demoted')], max_length=1)),
            ],
            bases=('the_keep.post',),
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='the_keep.post')),
                ('card_text', models.TextField()),
            ],
            bases=('the_keep.post',),
        ),
        migrations.CreateModel(
            name='Vagabond',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='the_keep.post')),
                ('animal', models.CharField(max_length=15)),
                ('ability_item', models.CharField(blank=True, choices=[('None', 'None'), ('Any', 'Any'), ('Torch', 'Torch'), ('Bag', 'Bag'), ('Tea', 'Tea'), ('Boots', 'Boots'), ('Coins', 'Coins'), ('Sword', 'Sword'), ('Hammer', 'Hammer'), ('Crossbow', 'Crossbow'), ('Other', 'Other')], max_length=150, null=True)),
                ('ability', models.CharField(max_length=150)),
                ('ability_description', models.TextField(blank=True, null=True)),
                ('starting_coins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('starting_boots', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('starting_bag', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('starting_tea', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('starting_hammer', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('starting_crossbow', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('starting_sword', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('starting_torch', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
            ],
            bases=('the_keep.post',),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('description', models.TextField(blank=True, null=True)),
                ('suited', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='the_keep.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('description', models.TextField(blank=True, null=True)),
                ('suited', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building', to='the_keep.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='expansion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='the_keep.expansion'),
        ),
        migrations.CreateModel(
            name='OtherPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('description', models.TextField(blank=True, null=True)),
                ('suited', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otherpiece', to='the_keep.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_gatehouse.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_keep.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarkedposts', through='the_keep.PostBookmark', to='the_gatehouse.profile'),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('description', models.TextField(blank=True, null=True)),
                ('suited', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token', to='the_keep.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warrior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('description', models.TextField(blank=True, null=True)),
                ('suited', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warrior', to='the_keep.post')),
            ],
            options={
                'verbose_name_plural': 'Warriors',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='the_keep.post')),
                ('clearings', models.IntegerField(default=12)),
                ('fixed_clearings', models.BooleanField(default=False)),
                ('default_landmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='the_keep.landmark')),
            ],
            bases=('the_keep.post',),
        ),
    ]
