# Generated by Django 5.1.2 on 2024-12-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_keep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagabond',
            name='ability_item',
            field=models.CharField(choices=[('None', 'None'), ('Any', 'Any'), ('Torch', 'Torch'), ('Bag', 'Bag'), ('Tea', 'Tea'), ('Boots', 'Boots'), ('Coins', 'Coins'), ('Sword', 'Sword'), ('Hammer', 'Hammer'), ('Crossbow', 'Crossbow'), ('Other', 'Other')], default='None', max_length=150),
        ),
    ]
