# Generated by Django 5.1.2 on 2024-11-20 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gatehouse', '0006_playerbookmark_profile_playerbookmarks'),
        ('the_keep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_gatehouse.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_keep.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarkedposts', through='the_keep.PostBookmark', to='the_gatehouse.profile'),
        ),
    ]
