# Generated by Django 5.1.2 on 2024-11-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_keep', '0002_postbookmark_post_bookmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='map',
            name='fixed_clearings',
            field=models.BooleanField(default=False),
        ),
    ]
