# Generated by Django 5.1.2 on 2024-12-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_keep', '0003_alter_post_options_map_fixed_clearings'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='in_root_digital',
            field=models.BooleanField(default=False),
        ),
    ]
