# Generated by Django 5.1.2 on 2024-12-02 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_gatehouse', '0007_rename_playerbookmarks_profile_bookmarks'),
        ('the_keep', '0004_post_in_root_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansion',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_gatehouse.profile'),
        ),
    ]
