# Generated by Django 5.1.2 on 2024-12-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_keep', '0005_alter_expansion_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansion',
            name='lore',
            field=models.TextField(blank=True, null=True),
        ),
    ]
