# Generated by Django 5.1.2 on 2024-12-04 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_keep', '0006_expansion_lore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expansion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='the_keep.expansion'),
        ),
    ]
