# Generated by Django 5.1.2 on 2024-12-06 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_keep', '0007_alter_post_expansion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-official', '-stable', '-date_posted']},
        ),
    ]
